### ISSUE TITLE
Header generation for C/C++

### ISSUE THREAD

**Issue by burner** [dlang/projects#4]
With the ever-improving integration between DMD and C/C++, quite a bit of tooling has been developed to generate D header files from C or C++ projects (e.g. (https://github.com/jacob-carlborg/dstep DStep) or (https://github.com/atilaneves/dpp DPP)).
However, for many projects the majority of the source code is now written in D and the reverse step is needed: an automatic way to generate C and C++ headers from a D project.
This would be very valuable for D as it could motivate inter-language projects that typically go C++-first-with-a-D-binding to work the other way.

Starting points:
*  [NG-Thread: "Make DMD emit C++ .h files same as .di files"](https://forum.dlang.org/post/mailman.7146.1551050711.29801.digitalmars-d@puremagic.com)
*  [Existing specialized work for the DMD codebase](https://github.com/dlang/dmd/pull/8591)
*  [Existing WIP work for generating C headers](https://gitlab.com/mihails.strasuns/dtoh)
* [ Existing WIP work for generating C++ headers, using DMD as a library](https://github.com/thewilsonator/dtoh)

**Comment by burner** [comment]
Is being worked on as a GSoC 2019 by 

@edi33416 
https://forum.dlang.org/thread/tlnarxbklplspauyetll@forum.dlang.org

**Comment by burner** [comment]
How to start:

-   [Simple
    example](https://github.com/dlang/dmd/blob/master/test/dub_package/frontend.d)
    of using DMD as a library
-   [More complex use cases](https://github.com/jacob-carlborg/dlp)

**Comment by lesderid** [comment]
@burner you forgot the `gsoc19` label on this one

**Comment by burner** [comment]
@lesderid thank you

**Comment by RazvanN7** [comment]
I think that we can close this one since the feature has been implemented.

**Comment by andre2007** [comment]
@RazvanN7 my understanding is, it was implemented for C++ but not for C. Did I missed s.th. ?

**Comment by UplinkCoder** [comment]
making the cpp header generator c compatible shouldn't be that bad,
but you are right, currently it's not.

**Comment by RazvanN7** [comment]
Indeed, the header generator was implemented for C++, however modifying it to work with C also should be fairly simple.

One other way to look at it is that  if you are going to call code that is written in the betterC subset of D, you can generate the C++ headers for your code and manually do some minor modifications like moving struct member functions to top-level.

My point is that most of the functionality is there so I don't know if this project makes sense anymore.

**Comment by wilzbach** [comment]
> I don't know if this project makes sense anymore.

Here's my thinking. We should open two new projects:
- header generation for C
- use generated header in LDC + GDC

Though both projects are not good fits for GSoC/SAoC as they both shouldn't take very long.
