### ISSUE TITLE
Start tagging with 'saoc'

### ISSUE THREAD

**Issue by GallaFrancesco** [dlang/projects#47]
In the light of the recent annoucement of SAoC 2019, we should start tagging appropriate projects with the 'saoc2019' tag. Possible targets:

* https://github.com/dlang/projects/issues/34
* https://github.com/dlang/projects/issues/32
* https://github.com/dlang/projects/issues/30
* https://github.com/dlang/projects/issues/24
* https://github.com/dlang/projects/issues/23
* https://github.com/dlang/projects/issues/22
* https://github.com/dlang/projects/issues/21
* https://github.com/dlang/projects/issues/20
* https://github.com/dlang/projects/issues/17
* https://github.com/dlang/projects/issues/16
* https://github.com/dlang/projects/issues/13
* https://github.com/dlang/projects/issues/3

**Comment by thewilsonator** [comment]
Label added.

**Comment by thewilsonator** [comment]
Tagged #2

**Comment by burner** [comment]
IMHO this tag should be called saoc. The idea are properly also valid for future saoc's. Adding a year limits the value of the label to much IMO.
If people choose a project to work on a comment with a link to the github should be added to the issue

**Comment by thewilsonator** [comment]
saoc for the projects year for the accepted ones?

**Comment by burner** [comment]
what about a github project for the accept ones?

**Comment by thewilsonator** [comment]
I don't think that is needed, IIRC accepted projects were to be closed and turned into project summaries after completion. Can't remember of this was ASoC, GSoC or both.

**Comment by burner** [comment]
okay. lets do it your suggested way

**Comment by thewilsonator** [comment]
Done.

**Comment by thewilsonator** [comment]
Added saoc2019 label, tagged: #2 , #51 , #54 

cc @SSoulaimane @maxhaton please add an issue to this repository for your projects (unless they're already there and I've missed them, in which case lmk and I'll add the relevant tags)

**Comment by maxhaton** [comment]
@thewilsonator #41 is what I'm working on. I've only got a phone (not even going to try tagging) for the next few days but I'll update with specifics if desired.


Max

**Comment by thewilsonator** [comment]
Thanks, done.

**Comment by SSoulaimane** [comment]
@thewilsonator tag this one please #55.

**Comment by thewilsonator** [comment]
Thanks, done.

**Comment by RazvanN7** [comment]
Maybe we can close this issue?

**Comment by burner** [comment]
sounds like a plan
