### ISSUE TITLE
Binding to OpenSSL 1.1.1d

### ISSUE THREAD

**Issue by zoujiaqing** [dlang/projects#60]
The latest version 1.1.1 is safety!

**Comment by Geod24** [comment]
I think that's just a matter of making  a PR to https://github.com/D-Programming-Deimos/openssl with the updated version ? Doesn't seem quite a fit for this repository, see: https://github.com/dlang/projects#browse-project-ideas

**Comment by zoujiaqing** [comment]
Thanks @Geod24 !
But, the `D-Programming-Deimos/openssl` is not updated!

**Comment by burner** [comment]
I agree with @Geod24 this does not belong here

**Comment by zoujiaqing** [comment]
@burner @Geod24 :
D language library is really too backward, after a year or not upgraded to openssl 1.1.1, and I am just an ordinary D language user.
