### ISSUE TITLE
ARC as default memory managerment！

### ISSUE THREAD

**Issue by zoujiaqing** [dlang/projects#70]
Like Swift, Objective-C and Nim:-)

https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html

**Comment by Geod24** [comment]
I don't think that is an issue fit for this. It's not something that is widely agreed on, nor something that has an obvious route to it. Something that is widely agreed on (but not with an obvious route either) is issue #27 , on which you commented with the same link. So closing as duplicate.

**Comment by wilzbach** [comment]
Nim allows the user to choose the memory management. In theory, the same could be done in D as well (an optional flag to the compiler that adds RC hooks instead of the GC ones). I don't think we should outright reject this idea.

**Comment by zoujiaqing** [comment]
Thanks @wilzbach
