### ISSUE TITLE
AArch32 / AArch64 support for intel-intrinsics

### ISSUE THREAD

**Issue by p0nce** [dlang/projects#71]
## Description

Like SIMDe, intel-intrinsics has the goal to program SIMD portably across ARM and x86, even if the base instrinsics are x86.

## What are rough milestones of this project?

- Complete MMX for AArch32 and AArch64
- Complete SSE1 for AArch32 and AArch64
- Complete SSE2 for AArch32 and AArch64
- Complete SSE3 for AArch32 and AArch64

AArch32 is much less important, being more about Rapsberry Pi portability.

## How does this project help the D community?

Optimizing with `intel-intrinsics` is very quick and yield fast results much more quickly than with assembly, and with more possibilities than just `core.simd`.
A prime example of this is dg2d, fastest software renderer in D: https://github.com/cerjones/dg2d

Recently there has been a surge of interest for libraries that abstract ARM and x86 intrinsics under either semantics: 
- https://github.com/simd-everywhere/simde
- https://github.com/DLTcollab/sse2neon

If D doesn't have this wrapper, making fast program will be more practical in C++ in a world split between x86 and ARM.

## Recommended skills

Interest in learning about compiler optimizations, in LLVM, and in fast programs.
Grit.
Correctness and detail-oriented.
This is thankless work with many subleties such as float rounding, float comparisons...

## What can students expect to get out of doing this project?

You will discover how much compiler backends like LLVM optimize, and it will change your way to write optimized code.

## Point of Contact

Guillaume Piolat, contact@auburnsounds.com

## References

- https://github.com/AuburnSounds/intel-intrinsics
- Introduction Talk: https://www.youtube.com/watch?v=cmswsx1_BUQ
- `intel-intrinsics` v1.0.0 forum announcement

**Comment by ibuclaw** [comment]
From what I recall from a GNU Cauldron talk, the PowerPC folks do the same thing too, and have a header with the same functions as mmintrin.h, but have power intrinsics used there instead.

**Comment by p0nce** [comment]
I've done it myself :) would be interesting to do it for ssse3 sse4.1 sse4.2 avx avx2 but it's a lot of work too
