### ISSUE TITLE
Baremetal D runtime

### ISSUE THREAD

**Issue by burner** [dlang/projects#9]
Many features in the standard library are implemented by using the C
runtime. Reusing the rock-solid work of generations of programmers makes
a lot of sense as just outputting via \`printf\` can be very
[complex](https://github.molgen.mpg.de/git-mirror/glibc/blob/20003c49884422da7ffbc459cdeee768a6fee07b/stdio-common/vfprintf.c).
However, for embedded environments a programmer often only has a tiny
amount of storage available or might not even have a C runtime available
for his target. The idea of this project is to implement the most basic
parts of the runtime natively in D, s.t. bare metals programmers can
just compile for their target. Implementing features natively in D also
means that other targets like [Web
Assembly](https://wiki.dlang.org/Generating_WebAssembly_with_LDC) will
automatically be able to use them too. Another advantage of implementing
these basic building blocks in D is that one can take advantage of D\'s
Compile-Time Function Evaluation (CTFE) and optimize the methods even
further at compile-time.

Project focus: - Implement `memcpy`, `memcmp` and similar in D (with
similar performance to C) - Implement \`malloc\` and similar in D (with
similar performance to C)

Starting points:

-   [D for Bare Metal Programming (tutorial
    series](https://theartofmachinery.com/2017/02/28/bare_metal_d.html)
-   [Simple demonstration of using D to bare-metal program an STM32F29I
    Discovery board](https://github.com/JinShil/stm32f42_discovery_demo)
-   [memcpyD](https://github.com/JinShil/memcpyD)
-   [Programming in D tutorial on Embedded Linux ARM
    devices](https://wiki.dlang.org/Programming_in_D_tutorial_on_Embedded_Linux_ARM_devices)

**Comment by baziotis** [comment]
This idea is pretty much this: https://github.com/dlang/projects/issues/26
project

**Comment by burner** [comment]
superseded by #26
